# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4e204e7a218ee877d94f6cd3e1550436558ad1aa3d884823179d2c1ec399b79e225b2ffc9a42029ab25818620f5049577d3bbde3c9f5408e6bef473d27233b2

test:
  secret_key_base: 8d25ebf1d9641b6a27bb2f5f193db5b3d36f12c94fbab98115f66ff4270ec8bf3fb60da25e90d9659543bc368cbe5823fa6452659c76c4c05ba512af9c506edd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
